server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:8761
  instance:
    hostname: localhost

spring:
  application:
    name: USER-SERVICE
